/**
 * Provides srcset and sizes for the shared hero/CTA image (hero-image).
 * Run `npm run optimize-images` to generate WebP responsive files; otherwise
 * the fallback PNG is used and srcset is omitted.
 */
export function useHeroImage() {
  const config = useRuntimeConfig()
  const baseURL = config.app?.baseURL ?? '/'

  const base = `${baseURL}images/hero-image`
  const fallbackSrc = `${base}.png`

  // Responsive WebP srcset (generated by npm run optimize-images)
  const srcsetWebP = `${base}-400w.webp 400w, ${base}-800w.webp 800w, ${base}-1200w.webp 1200w, ${base}-1920w.webp 1920w`

  // Reserve space and hint to browser which size to fetch
  const sizes =
    '(max-width: 640px) 100vw, (max-width: 1024px) 100vw, (max-width: 1280px) 100vw, 1920px'

  return {
    fallbackSrc,
    srcsetWebP,
    sizes,
  }
}
